### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by 0Motion0** [Neenja34/GMStranded-next#1]
Upon launching the game after following the instructions for singleplayer play; the console is immediately filled up with errors stating that various entities (weapons, effects) would attempt to intext a global 'SGS' that reads as a nil value, assumedly not existing.
![20230719005608_1](https://github.com/Neenja34/GMStranded-next/assets/139943634/84e89ebb-d40f-4b2b-95c7-def5b16b284c)
![20230719005547_1](https://github.com/Neenja34/GMStranded-next/assets/139943634/b39d3f6c-e9d4-40c4-8726-3c5d68834c6b)

**Comment by 0Motion0** [comment]
To note, I did follow the instructions to the letter; and it appears that the 'SGS' indexing is possibly referencing the 'mapsaves' file that comes with the GMStranded-master repository?

**Comment by 0Motion0** [comment]
To note, I did follow the instructions to the letter; and it appears that the 'SGS' indexing is possibly referencing the 'mapsaves' file that comes with the GMStranded-master repository?

**Comment by Neenja34** [comment]
It seems that you've got the classic version of Stranded installed - sadly you'll have to unsubscribe / uninstall the previous version of Stranded to install this one! I've added a note for it on the instructions as well, my apologies for that :D
